apiVersion: v1
kind: Service
metadata:
  name: nginx-prom-metrics
  namespace: nginx-ingress
  labels:
    app: nginx-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'http'
    prometheus.io/port: '9113'
    prometheus.io/path: '/metrics'
spec:
  selector:
    app: nginx-ingress-nginx-ingress
  ports:
    - port: 9113
      name: prometheus
      protocol: TCP
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemonitor
  namespace: nginx-ingress
  labels:
    release: prometheus
spec:
  endpoints:
    - interval: 5s
      port: prometheus
  selector:
    matchLabels:
      app: nginx-exporter